Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 840, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 721, in main
    loss, overflow, grad_norm = model.step(batch)
  File "/home/ubuntu/varuna/varuna/varuna.py", line 280, in step
    self.average_loss, fwd_time = self.pipeline.run()
  File "/home/ubuntu/varuna/varuna/pipeline.py", line 296, in run
    self.worker(task[0], grad_mode, self.batches[task[1]])
IndexError: list index out of range
terminate called without an active exception
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 840, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 721, in main
    loss, overflow, grad_norm = model.step(batch)
  File "/home/ubuntu/varuna/varuna/varuna.py", line 280, in step
    self.average_loss, fwd_time = self.pipeline.run()
  File "/home/ubuntu/varuna/varuna/pipeline.py", line 296, in run
    self.worker(task[0], grad_mode, self.batches[task[1]])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 840, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 601, in main
    device, args = setup_training(args)
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 349, in setup_training
    torch.distributed.init_process_group(backend='gloo' if args.varuna else 'nccl', init_method='env://')
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 232, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 160, in _create_c10d_store
    return TCPStore(
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 832, in handler
    print('Rank', torch.distributed.get_rank(), 'signal handler called with signal', signum, flush=True)
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 844, in get_rank
    default_pg = _get_default_group()
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
